/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 earth.glb --transform 
Files: earth.glb [18.93MB] > earth-transformed.glb [196.27KB] (99%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("./earth-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["Default OBJ"]}
      />
    </group>
  );
}

useGLTF.preload("./earth-transformed.glb");
