/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 mars.glb --transform 
Files: mars.glb [4.03MB] > mars-transformed.glb [132.13KB] (97%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function MarsP(props) {
  const { nodes, materials } = useGLTF("./mars-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube008.geometry}
        material={materials["Default OBJ.005"]}
      />
    </group>
  );
}

useGLTF.preload("./mars-transformed.glb");
